MindLeaps/tracker

Gemfile
Gemfile.lock
app/controllers/students_controller.rb
app/views/students/edit.html.erb
app/views/students/show.html.erb
config/routes.rb
spec/features/edit_student_spec.rb

Clicking on a student's name in index will take the user to a student's details page where there is an edit button. Clicking an edit button allows the user to edit student's details.
@j16r - can you take a look at this?

TRACK-12 - Added viewing and editing students

---

app/controllers/students_controller.rb
app/helpers/application_helper.rb
app/models/group.rb
app/models/student.rb
app/views/shared/_student_row.erb
app/views/shared/_students_table.erb
app/views/students/edit.html.erb
app/views/students/index.html.erb
app/views/students/show.html.erb
db/migrate/20160627235221_add_group_to_students.rb
db/schema.rb

@j16r - can you go over this stuff please?

Track 3 - Assigning students to groups

---

app/controllers/api/api_controller.rb
app/controllers/api/groups_controller.rb
app/controllers/api/students_controller.rb
config/routes.rb
spec/controllers/api_groups_controller_spec.rb
spec/controllers/api_students_controller_spec.rb
spec/fixtures/students.yml

Track 17 - Added JSON endpoints for retrieving students and groups

---

Gemfile
Gemfile.lock
app/controllers/api/grades_controller.rb
app/controllers/students_controller.rb
app/models/application_record.rb
app/models/grade.rb
app/models/student.rb
app/serializers/grade_serializer.rb
config/initializers/active_model_serializers.rb
config/routes.rb
db/migrate/20161013042217_add_timestamps_to_grades.rb
db/migrate/20161014032826_add_deleted_at_to_grades.rb
db/migrate/20161015235759_remove_grade_uniqueness_constraint.rb
db/schema.rb
spec/controllers/api_grades_controller_spec.rb
spec/controllers/students_controller_spec.rb
spec/models/grade_spec.rb
spec/models/student_spec.rb

included filtering by student, lesson, and timestamp.

Track 44 - Added API endpoints for submitting and retrieving grades

---

config/application.rb

:bowtie: @tomca32 
small cleanup, this option is no longer supported

Remove raise_in_transactional_callbacks, it has been retired

---

deploy/templates/nginx.conf

TRACK-19 Turn on strict transport security

---

db/migrate/20171115044314_add_keys.rb
db/schema.rb

Generated with https://github.com/jenseng/immigrant

Added missing foreign keys

---

CHANGELOG.md

- Upgraded Tiddle from 1.1.0 to 1.2.0
- Upgraded Rails from 5.1.5 to 5.1.6
- Upgraded New Relic agent from 4.8 to 5.0
- Upgraded Skylight from 1.5.1 to 1.6.0

0.4.2 Release

---

app/assets/stylesheets/application.scss
app/models/chapter.rb
app/models/group.rb
app/views/shared/_student_form.slim
app/views/shared/_students_table.slim
db/migrate/20210217042855_update_student_table_rows_to_version_2.rb
db/structure.sql
db/views/student_table_rows_v02.sql

- More obvious distinction between chapter and org MLIDs in student table
- Display chapter and org MLIDs in student form

Tom/1130 - MLID usability

---

app/controllers/api/assignments_controller.rb
app/controllers/api/subjects_controller.rb
app/policies/assignment_policy.rb
spec/policies/assignment_policy_spec.rb

- Added policy scoping for subjects and assignments

 1042: Delete organization resources after revoked access

---

app/controllers/groups_controller.rb
app/controllers/students_controller.rb
app/models/group.rb
app/views/groups/show.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/groups_controller_spec.rb

- Set deleted_at property for deleted/restored group and the same for dependents (students, lessons, grades)
- Tests for the same

1458: Group Deletion

---

CHANGELOG.md
app/views/analytics/general/index.html.erb
app/views/analytics/subject/index.html.erb

- Added flags so that No. of lessons and No. of assessments show up as whole numbers

1843: Chart decimal values

---

app/controllers/analytics/general_controller.rb
app/controllers/analytics/group_controller.rb
app/controllers/analytics/subject_controller.rb
app/views/analytics/general/index.html.erb
app/views/analytics/group/index.html.erb
app/views/analytics/subject/index.html.erb

Feature for #1939 
- Increment x-axis values for 'No. of Lessons' so as to start from 1
- Limit grades to go up to 7

1939: Graph values

---

app/views/student_lessons/show.turbo_stream.erb
config/locales/en.yml

- Added 'Ungraded' text for blank selection when grading students in a lesson

1971: Add 'Ungraded' for blank grades

---

db/migrate/20240828172524_fix_enrollments_data.rb
db/structure.sql

- Added migration fix for enrollments
- Logic was done according to the chart found below

1990: Fix enrollments data

---

CHANGELOG.md
app/assets/javascripts/charts.js
db/structure.sql

Seems to include changes in structure.sql
I assume those are changes done by previous migrations but seems `structure.sql` was not commited.

Fixed graph in single lesson view to properly highlight current lesson

---

CHANGELOG.md
app/assets/javascripts/charts.js
app/controllers/group_reports_controller.rb
app/helpers/application_helper.rb
app/helpers/collection_helper.rb
app/models/group_lesson_summary.rb
app/views/group_reports/show.html.erb
app/views/layouts/print.html.erb
config/locales/en.yml
db/migrate/20240917090713_add_attendance_to_group_lesson_summaries.rb
db/structure.sql
db/views/group_lesson_summaries_v05.sql
spec/features/reports_features_spec.rb
spec/models/group_lesson_summary_spec.rb

- Added attendance to group lesson summaries
- Added attendance bar chart in reports page
- Added attendance checks in group lesson summary spec

2023: Attendance Graph Reports

---

app/helpers/collection_helper.rb
spec/helpers/collection_helper_spec.rb

- Fixed collection helper method
- Added unit tests for the helper

Fix: Fix collection helper method and add unit tests

---

CHANGELOG.md
app/assets/javascripts/charts.js
app/views/groups/show.html.erb
config/locales/en.yml
spec/features/group_features_spec.rb

- Added button for generating report in group view
- Some minor tweaks for better looking report
- Test for the same

2031: Button for generating reports

---

CHANGELOG.md
app/components/table_components/student_enrollment_report.rb
app/controllers/group_reports_controller.rb
app/views/group_reports/show.html.erb
app/views/groups/show.html.erb
app/views/layouts/print.html.erb
config/locales/en.yml
spec/features/group_features_spec.rb
spec/features/reports_features_spec.rb

- Added table and separate component for enrolled students in reports page, gathering info from enrollments
- Added check for report button being displayed in group view
- Modified tests

2023: Enrolled students in group report

---

CHANGELOG.md
app/components/table_components/student_row.rb

- Added gender column to student row component

Enhancement: Show gender in student tables

---

app/views/analytics/general/index.html.erb

- Added tick positions for all scores in chart
- Added trendlines for chart if series length is 3 or less

Enhancement: Add ticks and trendlines to average group performance in analytics

---

CHANGELOG.md
app/controllers/analytics/group_controller.rb

- Modified regression flag in group controller for analytics

1975: Fix missing data in group analytics

---

app/assets/javascripts/charts.js
app/controllers/group_reports_controller.rb
app/views/group_reports/show.html.erb
spec/features/reports_features_spec.rb

- Added fallback values in controller
- Added some basic visual handling in the report view
- Added a test to check for empty group reports

2068: Handle empty Group Reports

---

app/components/table_components/table.rb
config/tailwind.config.js

- Removed extra closing tag causing visual issue
- Removed redundant tailwind config

Fix: Single lesson view

---

app/components/datepicker.rb

- Added flag to disable autocomplete in datepicker component

Disable autocomplete for datepicker

---

app/assets/javascripts/charts.js
app/controllers/group_reports_controller.rb
app/views/group_reports/show.html.erb
app/views/layouts/print.html.erb

- Fixed constructor call when rendering timeline chart
- Added checks for group history and performance charts
- Modified printout look

2162: Fix group reports

---

CHANGELOG.md
app/components/common_components/toggle_component.html.erb
app/components/common_components/toggle_component.rb
app/views/group_reports/show.html.erb
spec/components/toggle_component_spec.rb

- Added section in group reports containing toggle menu
- Hide/Show each component when toggles are clicked

2170: Report toggles

---

app/controllers/students_controller.rb
app/models/student_lesson.rb
spec/test_helpers/compat.rb

- Amended lint errors
- Could not recreate failed test suites with current failing PR seeds, will merge to have new seeds be created

2229: Cleanup lint errors & flaky tests

---

CHANGELOG.md
app/views/analytics/subject/index.html.erb

- Updated subject analytics performance charts to show each score

2263: Update subject analytics performance charts to show each score
